### ISSUE TITLE
Errors handling single-record files

### ISSUE THREAD

**Issue by jvolkening** [lrog/dsrc#13]
I am using the latest commit on the 'devel' branch on 64-bit Linux.

The edge case consisting of a FASTQ file w/ a single record seems to cause problems. Attempting to compress with the main dsrc binary throws:

"Error: Error analyzing FASTQ dataset"

Compressing using the DsrcArchive API (e.g. "example2") apparently succeeds but decompressing the resulting file using either the main binary or DsrcArchive API throws:

"Error: Corrupted DSRC archive header"

If the FASTQ file is modified to include a second, identical record the errors disappear.

An example of a "toy" FASTQ file that causes the errors described:

```
@test1
ATGCATGC
+
99999999
```

**Comment by lrog** [comment]
Thanks for the report and sorry for a late response. Thanks for your fix! I've just merged it to devel branch and slightly altered in 485316eaef971fcb46603b62ae4df3df1d707b84 . 
The return condition 'records count > 1' was not fully correct and was used mainly to ensure that the archive is not of mixed type - both color space and standard Illumina / 454.
